### ISSUE TITLE
Connect Docker to Database on AWS

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-group7-cloud#6]
# Summary
The newest commit added some example code connecting to a database. However, I only test it to work on my machine.
![image](https://github.com/ClementineAccount/csd3156-group7-cloud/assets/26779639/13190b08-81b5-4fdb-be9e-20c8f531db58)

https://github.com/ClementineAccount/csd3156-group7-cloud/assets/26779639/3b52ff0a-3a82-4008-9d4e-e53f9efda7ac

![image](https://github.com/ClementineAccount/csd3156-group7-cloud/assets/26779639/aedb0f01-4132-4f03-99b6-46c8f8fa6935)

What needs to be done is edit that to use the AWS RDS login stuff instead. However, one thing to note is that the code expects a table named 'student' to be created first. So create that first.

![image](https://github.com/ClementineAccount/csd3156-group7-cloud/assets/26779639/5c1d0999-6a2c-49dc-8cb9-c18ed383be91)

The 'student' data is because was using this as a tutorial for making sure the tech stack is working: 
https://www.digitalocean.com/community/tutorials/how-to-use-flask-sqlalchemy-to-interact-with-databases-in-a-flask-application

# Task List 

- [ ] Add 'student' table to the database `messages`
- [ ] (flask_test.py) Edit `'mysql+pymysql://clem:testtest@172.18.32.1:3306/database_real`' to something like `mysql+pymysql://Admin:testtest@team7-database.cxa8ke4g2fp3.us-east-1.rds.amazonaws.com/messages`
- [ ] Run the Docker inside the EC2.
- [ ] Check if it connects. If it connects upload video or screenshot here and do pull request.

**Comment by ClementineAccount** [comment]
Completed today by @ClementineAccount @recon68 @VentusFlame and @Green80X in lecture hall.
